namespace SageTUI

open System

[<Flags>]
type Modifiers =
  | None = 0
  | Shift = 1
  | Alt = 2
  | Ctrl = 4
  | Meta = 8

type Key =
  | Char of char
  | Enter | Escape | Backspace | Tab
  | Up | Down | Left | Right
  | Home | End | PageUp | PageDown
  | Insert | Delete
  | F of int

type MouseButton = LeftButton | RightButton | MiddleButton | ScrollUp | ScrollDown

/// Whether the mouse button went down (Pressed), came up (Released), or was held
/// during motion (Motion). Released corresponds to the lowercase 'm' SGR terminator;
/// Motion is generated by button-event tracking mode (?1002h) when the terminal sends
/// an event with the motion flag (btn & 32) set.
type MousePhase = Pressed | Released | Motion

type MouseEvent =
  { Button: MouseButton; X: int; Y: int; Modifiers: Modifiers; Phase: MousePhase }

type TerminalEvent =
  | KeyPressed of key: Key * modifiers: Modifiers
  | MouseInput of MouseEvent
  | Resized of width: int * height: int
  | FocusGained
  | FocusLost
  | Pasted of string

/// Pure ANSI/VT escape sequence parser. No I/O — feeds into the background input reader.
module AnsiParser =

  /// Parse an SGR extended mouse CSI body.
  /// Input format (body after '\x1b['): "<btn;x;yM" (press/motion) or "<btn;x;ym" (release)
  ///
  /// SGR btn bit layout:
  ///   0-1  button (0=left, 1=middle, 2=right)
  ///   2    shift
  ///   3    alt
  ///   4    ctrl
  ///   5    motion flag — set by button-event tracking (?1002h) when the button is held
  ///   6    scroll flag — when set, bit 0 picks direction (0=up, 1=down)
  ///
  /// Coordinates are 1-indexed in the wire format; returned X/Y are 0-indexed.
  let parseSgrMouse (csiBody: string) : MouseEvent option =
    if csiBody.Length < 5 || csiBody.[0] <> '<' then None
    else
      let terminator = csiBody.[csiBody.Length - 1]
      match terminator with
      | 'M' | 'm' ->
        let inner = csiBody.[1..csiBody.Length - 2]  // strip '<' and M/m terminator
        let parts = inner.Split(';')
        match parts.Length with
        | 3 ->
          match Int32.TryParse(parts.[0]), Int32.TryParse(parts.[1]), Int32.TryParse(parts.[2]) with
          | (true, btn), (true, x), (true, y) ->
            let phase =
              match terminator with
              | 'm' -> Released
              | _ ->
                match btn &&& 32 <> 0 with
                | true -> Motion
                | false -> Pressed
            // Strip motion flag before classifying button — bit 32 doesn't change which button
            let rawBtn = btn &&& ~~~32
            let button =
              match rawBtn &&& 64 <> 0, rawBtn &&& 3 with
              | true, 0 -> ScrollUp
              | true, _ -> ScrollDown
              | false, 0 -> LeftButton
              | false, 1 -> MiddleButton
              | false, _ -> RightButton
            let mutable m = Modifiers.None
            if btn &&& 4  <> 0 then m <- m ||| Modifiers.Shift
            if btn &&& 8  <> 0 then m <- m ||| Modifiers.Alt
            if btn &&& 16 <> 0 then m <- m ||| Modifiers.Ctrl
            Some { Button = button; X = x - 1; Y = y - 1; Modifiers = m; Phase = phase }
          | _ -> None
        | _ -> None
      | _ -> None

  /// Returns true when the accumulated buffer (everything AFTER the ESC byte)
  /// forms a syntactically complete VT escape sequence.
  let isCompleteEscSeq (buf: string) : bool =
    match buf with
    | "" -> false
    | s ->
      match s.[0] with
      | '[' ->
        // CSI: '[' + zero-or-more param/intermediate bytes + one final byte (0x40–0x7E)
        s.Length >= 2 && s.[s.Length - 1] >= '@' && s.[s.Length - 1] <= '~'
      | 'O' ->
        // SS3: 'O' + exactly one char (F1=P, F2=Q, F3=R, F4=S)
        s.Length = 2
      | _ ->
        // Alt+key: single char after ESC
        s.Length = 1

  /// Parse the accumulated sequence buffer (AFTER the ESC byte) into a TerminalEvent.
  ///
  /// Returns None only for genuinely unrecognised sequences where emitting Escape is the
  /// correct fallback. Alt+key sequences (single char after ESC) are always recognised —
  /// they return `Some (KeyPressed(Key.Char c, Modifiers.Alt))`. Unrecognised CSI/SS3
  /// sequences return None so the caller can emit a bare Escape key.
  let parseEscape (rest: string) : TerminalEvent option =
    match rest with
    | "[A" -> Some (KeyPressed(Key.Up,       Modifiers.None))
    | "[B" -> Some (KeyPressed(Key.Down,     Modifiers.None))
    | "[C" -> Some (KeyPressed(Key.Right,    Modifiers.None))
    | "[D" -> Some (KeyPressed(Key.Left,     Modifiers.None))
    | "[H" | "[1~" | "[7~" -> Some (KeyPressed(Key.Home,    Modifiers.None))
    | "[F" | "[4~" | "[8~" -> Some (KeyPressed(Key.End,     Modifiers.None))
    | "[2~" -> Some (KeyPressed(Key.Insert,  Modifiers.None))
    | "[3~" -> Some (KeyPressed(Key.Delete,  Modifiers.None))
    | "[5~" -> Some (KeyPressed(Key.PageUp,  Modifiers.None))
    | "[6~" -> Some (KeyPressed(Key.PageDown,Modifiers.None))
    | "OP"  -> Some (KeyPressed(Key.F 1,     Modifiers.None))
    | "OQ"  -> Some (KeyPressed(Key.F 2,     Modifiers.None))
    | "OR"  -> Some (KeyPressed(Key.F 3,     Modifiers.None))
    | "OS"  -> Some (KeyPressed(Key.F 4,     Modifiers.None))
    | "[15~" -> Some (KeyPressed(Key.F 5,   Modifiers.None))
    | "[17~" -> Some (KeyPressed(Key.F 6,   Modifiers.None))
    | "[18~" -> Some (KeyPressed(Key.F 7,   Modifiers.None))
    | "[19~" -> Some (KeyPressed(Key.F 8,   Modifiers.None))
    | "[20~" -> Some (KeyPressed(Key.F 9,   Modifiers.None))
    | "[21~" -> Some (KeyPressed(Key.F 10,  Modifiers.None))
    | "[23~" -> Some (KeyPressed(Key.F 11,  Modifiers.None))
    | "[24~" -> Some (KeyPressed(Key.F 12,  Modifiers.None))
    // Terminal OS-level focus reporting (?1004h): ESC [ I = gained, ESC [ O = lost
    | "[I"  -> Some FocusGained
    | "[O"  -> Some FocusLost
    | s when s.Length > 2 && s.[0] = '[' && s.[1] = '<' ->
      // SGR mouse: CSI body is "[<btn;x;yM" → pass "<btn;x;yM" to parseSgrMouse
      parseSgrMouse s.[1..] |> Option.map MouseInput
    | s when s.Length = 1 ->
      // Alt+key: ESC followed by a single character (e.g. ESC+'a' = Alt+a)
      // This MUST come after the CSI/SS3 patterns so "[" doesn't match here.
      Some (KeyPressed(Key.Char s.[0], Modifiers.Alt))
    | _ -> None
